"""
Spot Render IA Auto Agents - Runbook Generator Capability
=====================================================

This module provides the capability to automatically generate runbooks
for detected issues and incidents.

PT-BR: Módulo para gerar automaticamente runbooks para problemas e incidentes detectados.
EN-US: Module to automatically generate runbooks for detected issues and incidents.

Features:
- Generate runbooks from alert context
- Include diagnostic steps
- Include resolution procedures
- Include prevention recommendations
- Support multiple formats (Markdown, HTML)
"""

import json
import logging
from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, List, Optional, Any
from pathlib import Path

logger = logging.getLogger(__name__)


@dataclass
class RunbookStep:
    """A single step in a runbook."""
    order: int
    title: str
    command: str = ""
    description: str = ""
    expected_output: str = ""
    verification_command: str = ""
    timeout_seconds: int = 30
    critical: bool = False


@dataclass
class Runbook:
    """
    Complete runbook for an issue.

    PT-BR: Runbook completo para um problema.
    EN-US: Complete runbook for an issue.
    """
    # Identity
    runbook_id: str
    title: str
    issue_type: str
    severity: str

    # Content
    overview: str = ""
    prerequisites: List[str] = field(default_factory=list)
    steps: List[RunbookStep] = field(default_factory=list)
    verification_steps: List[str] = field(default_factory=list)
    rollback_steps: List[str] = field(default_factory=list)
    prevention: List[str] = field(default_factory=list)

    # Metadata
    created_at: datetime = field(default_factory=datetime.now)
    updated_at: datetime = field(default_factory=datetime.now)
    created_by: str = "AI Agent"
    version: str = "1.0.0"
    tags: List[str] = field(default_factory=list)

    # Related
    related_alerts: List[str] = field(default_factory=list)
    related_incidents: List[str] = field(default_factory=list)
    dashboard_url: str = ""

    def to_markdown(self) -> str:
        """Generate markdown documentation for the runbook."""
        steps_md = ""
        for step in self.steps:
            critical_marker = " 🔴" if step.critical else ""
            steps_md += f"""
### {step.order}. {step.title}{critical_marker}

**Description:** {step.description}

"""
            if step.command:
                steps_md += f"```bash\n{step.command}\n```\n\n"
            if step.expected_output:
                steps_md += f"**Expected Output:** `{step.expected_output}`\n\n"
            if step.verification_command:
                steps_md += f"**Verification:** ` {step.verification_command}`\n\n"

        verification_md = ""
        for i, step in enumerate(self.verification_steps, 1):
            verification_md += f"{i}. {step}\n"

        rollback_md = ""
        for i, step in enumerate(self.rollback_steps, 1):
            rollback_md += f"{i}. {step}\n"

        prevention_md = ""
        for item in self.prevention:
            prevention_md += f"- {item}\n"

        tags_md = ", ".join(f"`{t}`" for t in self.tags)

        return f"""# Runbook: {self.title}

## Metadata

| Field | Value |
|-------|-------|
| **ID** | `{self.runbook_id}` |
| **Issue Type** | {self.issue_type} |
| **Severity** | {self.severity} |
| **Version** | {self.version} |
| **Created** | {self.created_at.isoformat()} |
| **Updated** | {self.updated_at.isoformat()} |
| **Created By** | {self.created_by} |
| **Tags** | {tags_md} |

## Overview

{self.overview}

## Prerequisites

{"".join(f"- {p}" for p in self.prerequisites)}

## Procedure

{steps_md}

## Verification

{verification_md if verification_md else "_No verification steps defined_"}

## Rollback

{rollback_md if rollback_md else "_No rollback needed_"}

## Prevention

{prevention_md if prevention_md else "_No prevention recommendations yet_"}

## Related

{"".join(f"- Alert: `{a}`" for a in self.related_alerts)}

{"".join(f"- Incident: `{i}`" for i in self.related_incidents)}

{"".join(f"- Dashboard: [View]({self.dashboard_url})") if self.dashboard_url else ""}

---
_Generated by Spot Render AI Agents on {datetime.now().isoformat()}_
_This runbook is automatically generated and should be reviewed before use._
"""


class RunbookGenerator:
    """
    Automatically generates runbooks from detected issues.

    PT-BR: Gera automaticamente runbooks a partir de problemas detectados.
    EN-US: Automatically generates runbooks from detected issues.
    """

    # Templates for common issue types
    ISSUE_TEMPLATES = {
        "pod_crash": {
            "title": "Pod Crash Investigation and Resolution",
            "overview": "This runbook covers the investigation and resolution of crashing pods.",
            "prerequisites": [
                "kubectl access to the cluster",
                "Permission to view pods and logs",
                "Permission to exec into pods"
            ],
            "prevention": [
                "Implement proper resource limits",
                "Set up health checks (liveness/readiness)",
                "Monitor memory and CPU usage",
                "Use appropriate restart policies"
            ]
        },
        "high_latency": {
            "title": "High Latency Investigation",
            "overview": "This runbook covers investigation of high latency issues.",
            "prerequisites": [
                "Access to monitoring dashboards",
                "kubectl access to the cluster",
                "Access to application logs"
            ],
            "prevention": [
                "Implement caching strategies",
                "Set up latency SLOs and alerts",
                "Use appropriate timeouts",
                "Implement circuit breakers"
            ]
        },
        "oom_kill": {
            "title": "OOM Kill Investigation and Resolution",
            "overview": "This runbook covers investigation of Out of Memory kills.",
            "prerequisites": [
                "kubectl access to the cluster",
                "Access to node metrics",
                "Permission to modify resource limits"
            ],
            "prevention": [
                "Set appropriate memory limits",
                "Monitor memory usage trends",
                "Implement memory profiling",
                "Use appropriate container memory limits"
            ]
        },
        "deployment_issues": {
            "title": "Deployment Issues Resolution",
            "overview": "This runbook covers common deployment problems.",
            "prerequisites": [
                "kubectl access to the cluster",
                "Permission to manage deployments",
                "Access to CI/CD logs"
            ],
            "prevention": [
                "Use proper health checks",
                "Implement rolling updates",
                "Set appropriate resource requests/limits",
                "Use deployment strategies appropriate for the workload"
            ]
        },
        "network_issues": {
            "title": "Network Connectivity Issues",
            "overview": "This runbook covers investigation of network problems.",
            "prerequisites": [
                "kubectl access to the cluster",
                "Permission to view network policies",
                "Access to service mesh dashboards (if applicable)"
            ],
            "prevention": [
                "Implement network policies",
                "Use appropriate service mesh configuration",
                "Set up connectivity tests in CI/CD",
                "Monitor network metrics"
            ]
        }
    }

    def __init__(self, storage_path: str = "/var/log/agents/runbooks"):
        self.storage_path = Path(storage_path)
        self.storage_path.mkdir(parents=True, exist_ok=True)
        self.generated_runbooks: Dict[str, Runbook] = {}

    def generate_runbook(
        self,
        issue_type: str,
        context: Dict[str, Any],
        severity: str = "warning"
    ) -> Runbook:
        """
        Generate a runbook based on issue type and context.

        PT-BR: Gera um runbook baseado no tipo de problema e contexto.
        EN-US: Generates a runbook based on issue type and context.
        """
        # Get template or create generic
        template = self.ISSUE_TEMPLATES.get(issue_type, {
            "title": f"Runbook: {issue_type}",
            "overview": "Auto-generated runbook",
            "prerequisites": ["kubectl access"],
            "prevention": []
        })

        # Generate runbook ID
        runbook_id = f"rb-{issue_type}-{datetime.now().strftime('%Y%m%d%H%M%S')}"

        runbook = Runbook(
            runbook_id=runbook_id,
            title=template["title"],
            issue_type=issue_type,
            severity=severity,
            overview=template["overview"],
            prerequisites=template["prerequisites"],
            prevention=template["prevention"],
            created_by="AI Agent",
            tags=[issue_type, "auto-generated"]
        )

        # Generate steps based on issue type
        runbook.steps = self._generate_steps(issue_type, context)

        # Add verification steps
        runbook.verification_steps = self._generate_verification_steps(issue_type)

        # Add rollback steps
        runbook.rollback_steps = self._generate_rollback_steps(issue_type)

        # Store and save
        self.generated_runbooks[runbook_id] = runbook
        self._save_runbook(runbook)

        logger.info(f"Generated runbook: {runbook_id} for issue: {issue_type}")

        return runbook

    def _generate_steps(self, issue_type: str, context: Dict[str, Any]) -> List[RunbookStep]:
        """Generate diagnostic and resolution steps."""
        steps = []

        # Common initial diagnostic steps
        steps.append(RunbookStep(
            order=1,
            title="Check Current Status",
            description="Get current status of affected resources",
            command=f"kubectl get pods -n {context.get('namespace', '<namespace>')} | grep {context.get('resource_name', '<name>')}",
            expected_output="Pod status (Running, CrashLoopBackOff, etc.)",
            critical=True
        ))

        steps.append(RunbookStep(
            order=2,
            title="Check Pod Events",
            description="View recent events for the pod",
            command=f"kubectl describe pod -n {context.get('namespace', '<namespace>')} {context.get('resource_name', '<name>')} | grep -A10 Events",
            expected_output="Recent events including last state changes"
        ))

        steps.append(RunbookStep(
            order=3,
            title="Check Pod Logs",
            description="View recent logs from the pod",
            command=f"kubectl logs -n {context.get('namespace', '<namespace>')} {context.get('resource_name', '<name>')} --tail=100",
            expected_output="Application logs showing error messages"
        ))

        # Issue-specific steps
        if issue_type == "pod_crash":
            steps.append(RunbookStep(
                order=4,
                title="Check Previous Logs",
                description="View logs from previous container instance",
                command=f"kubectl logs -n {context.get('namespace', '<namespace>')} {context.get('resource_name', '<name>')} --previous",
                expected_output="Logs from the crashed container"
            ))

            steps.append(RunbookStep(
                order=5,
                title="Check Resource Limits",
                description="Verify if pod hit resource limits",
                command=f"kubectl describe pod -n {context.get('namespace', '<namespace>')} {context.get('resource_name', '<name>')} | grep -A5 Limits",
                expected_output="CPU and Memory limits"
            ))

        elif issue_type == "high_latency":
            steps.append(RunbookStep(
                order=4,
                title="Check Current Metrics",
                description="View current latency metrics",
                command="kubectl top pods | sort -k3 -rn | head -10",
                expected_output="Top pods by resource usage"
            ))

            steps.append(RunbookStep(
                order=5,
                title="Check Service Endpoints",
                description="Verify service has healthy endpoints",
                command=f"kubectl get endpoints -n {context.get('namespace', '<namespace>')} {context.get('resource_name', '<name>')}",
                expected_output="List of ready pod IPs"
            ))

        elif issue_type == "oom_kill":
            steps.append(RunbookStep(
                order=4,
                title="Check Node Memory",
                description="View node memory status",
                command="kubectl top nodes",
                expected_output="Memory usage per node"
            ))

            steps.append(RunbookStep(
                order=5,
                title="Check OOM Events",
                description="Search for OOM events in the cluster",
                command="kubectl get events --all-namespaces | grep OOM",
                expected_output="OOM kill events"
            ))

        # Common resolution steps
        steps.append(RunbookStep(
            order=6,
            title="Implement Fix",
            description="Apply the appropriate fix based on diagnosis",
            command=f"kubectl rollout restart deployment/{context.get('resource_name', '<name>')} -n {context.get('namespace', '<namespace>')}",
            verification_command=f"kubectl rollout status deployment/{context.get('resource_name', '<name>')} -n {context.get('namespace', '<namespace>')}",
            timeout_seconds=300,
            critical=True
        ))

        return steps

    def _generate_verification_steps(self, issue_type: str) -> List[str]:
        """Generate verification steps."""
        steps = [
            "Verify pod is Running with `kubectl get pods`",
            "Check application logs are clean of errors",
            "Verify metrics return to normal levels",
            "Confirm affected services are responding"
        ]
        return steps

    def _generate_rollback_steps(self, issue_type: str) -> List[str]:
        """Generate rollback steps."""
        steps = []
        if issue_type == "deployment_issues":
            steps.append("Rollback deployment: `kubectl rollout undo deployment/<name>`")
            steps.append("Verify rollback completed: `kubectl rollout status deployment/<name>`")
        return steps

    def _save_runbook(self, runbook: Runbook):
        """Save runbook to storage."""
        runbook_file = self.storage_path / f"{runbook.runbook_id}.md"
        with open(runbook_file, 'w') as f:
            f.write(runbook.to_markdown())

        # Also save JSON metadata
        metadata_file = self.storage_path / f"{runbook.runbook_id}.json"
        with open(metadata_file, 'w') as f:
            json.dump({
                "runbook_id": runbook.runbook_id,
                "title": runbook.title,
                "issue_type": runbook.issue_type,
                "severity": runbook.severity,
                "created_at": runbook.created_at.isoformat(),
                "created_by": runbook.created_by,
                "tags": runbook.tags
            }, f, indent=2)

    def get_runbook(self, runbook_id: str) -> Optional[Runbook]:
        """Get a runbook by ID."""
        return self.generated_runbooks.get(runbook_id)

    def list_runbooks(self) -> List[Runbook]:
        """List all generated runbooks."""
        return list(self.generated_runbooks.values())


# Global instance
_runbook_generator: Optional[RunbookGenerator] = None


def get_runbook_generator() -> RunbookGenerator:
    """Get or create the global RunbookGenerator instance."""
    global _runbook_generator
    if _runbook_generator is None:
        _runbook_generator = RunbookGenerator()
    return _runbook_generator
